
package com.devsakatsuki.perfumariapi2.view;

import com.devsakatsuki.perfumariapi2.dao.ConexaoBD;
import com.devsakatsuki.perfumariapi2.dao.ProdutoDAO;
import com.devsakatsuki.perfumariapi2.model.Produto;
import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class JProduto2 extends javax.swing.JInternalFrame {
    
    //Variaveis globais
    ConexaoBD conexao = new ConexaoBD();
    ProdutoDAO pro = new ProdutoDAO(conexao.abrirConexao());
    
    Locale br = new Locale("pt", "Brazil");
    NumberFormat nf = NumberFormat.getInstance(br);

    /** Creates new form JProduto2 */
    public JProduto2() {
        initComponents();
        carregaTabela();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ComboPesquisa = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTbProduto = new javax.swing.JTable();
        jBtnNovo = new javax.swing.JButton();
        jBtnEditar = new javax.swing.JButton();
        jBtnExcluir = new javax.swing.JButton();
        txtPesquisa = new javax.swing.JTextField();
        btnPesquisa = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Produtos");
        setPreferredSize(new java.awt.Dimension(670, 500));

        jLabel1.setText("Produto");

        ComboPesquisa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Código", "Nome", "Categoria", "Marca", "Todos" }));
        ComboPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboPesquisaActionPerformed(evt);
            }
        });

        jTbProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Preço", "Quantidade", "Categoria", "Marca"
            }
        ));
        jScrollPane2.setViewportView(jTbProduto);

        jBtnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/new_file_16.png"))); // NOI18N
        jBtnNovo.setText("Novo");
        jBtnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNovoActionPerformed(evt);
            }
        });

        jBtnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/editar.png"))); // NOI18N
        jBtnEditar.setText("Editar");
        jBtnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEditarActionPerformed(evt);
            }
        });

        jBtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lixeira.png"))); // NOI18N
        jBtnExcluir.setText("Excluir");
        jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirActionPerformed(evt);
            }
        });

        txtPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisaActionPerformed(evt);
            }
        });

        btnPesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pesquisar.png"))); // NOI18N
        btnPesquisa.setText("Pesquisar");
        btnPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 607, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ComboPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPesquisa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBtnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnNovo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPesquisa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ComboPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisa))
                .addGap(24, 24, 24)
                .addComponent(jBtnNovo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnExcluir)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboPesquisaActionPerformed

    private void jBtnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNovoActionPerformed
        JProdutoInserir2 jpi = new JProdutoInserir2();
        jpi.mostraTela(this);
        
        
    }//GEN-LAST:event_jBtnNovoActionPerformed

    private void txtPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisaActionPerformed

    private void btnPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaActionPerformed
        // TODO add your handling code here:
        if(ComboPesquisa.getSelectedItem().toString().equalsIgnoreCase("Código")){
            try{
                
            Produto p = pro.getProdutoId(Integer.valueOf(txtPesquisa.getText()));    
                
            DefaultTableModel tblProduto = (DefaultTableModel)jTbProduto.getModel();
        
            tblProduto.setNumRows(0);
            
            tblProduto.addRow(new Object []{
                p.getCodigo(),
                p.getNome(),
                nf.format(p.getPreco()),
                p.getQuantidade(),
                p.getCategoria(),
                p.getMarca()
            });
            
                
            }catch(Exception ex){
                JOptionPane.showMessageDialog(null,"Erro ao consultar produto", ex.getMessage(), JOptionPane.WARNING_MESSAGE);
            }
        } else if(ComboPesquisa.getSelectedItem().toString().equalsIgnoreCase("Nome")){
            try{
                          
            DefaultTableModel tblProduto = (DefaultTableModel)jTbProduto.getModel();
        
            tblProduto.setNumRows(0);
            
            for(Produto p: pro.getProdutoNome(txtPesquisa.getText())){
                tblProduto.addRow(new Object []{
                    p.getCodigo(),
                    p.getNome(),
                    nf.format(p.getPreco()),
                    p.getQuantidade(),
                    p.getCategoria(),
                    p.getMarca()
                });
            }
                
            }catch(Exception ex){
                JOptionPane.showMessageDialog(null,"Erro ao consultar produto", ex.getMessage(), JOptionPane.WARNING_MESSAGE);
            }
        }else if(ComboPesquisa.getSelectedItem().toString().equalsIgnoreCase("Marca")){
            try{
                                     
            DefaultTableModel tblProduto = (DefaultTableModel)jTbProduto.getModel();
        
            tblProduto.setNumRows(0);
            
            for(Produto p: pro.getProdutoMarca(txtPesquisa.getText())){
                tblProduto.addRow(new Object []{
                   p.getCodigo(),
                    p.getNome(),
                    nf.format(p.getPreco()),
                    p.getQuantidade(),
                    p.getCategoria(),
                    p.getMarca()
                });
            }
                
            }catch(Exception ex){
                JOptionPane.showMessageDialog(null,"Erro ao consultar produto", ex.getMessage(), JOptionPane.WARNING_MESSAGE);
            }
        }else if(ComboPesquisa.getSelectedItem().toString().equalsIgnoreCase("Categoria")){
            try{
                                     
            DefaultTableModel tblProduto = (DefaultTableModel)jTbProduto.getModel();
        
            tblProduto.setNumRows(0);
            
            for(Produto p: pro.getProdutoCategoria(txtPesquisa.getText())){
                tblProduto.addRow(new Object []{
                   p.getCodigo(),
                    p.getNome(),
                    nf.format(p.getPreco()),
                    p.getQuantidade(),
                    p.getCategoria(),
                    p.getMarca()
                });
            }
                
            }catch(Exception ex){
                JOptionPane.showMessageDialog(null,"Erro ao consultar produto", ex.getMessage(), JOptionPane.WARNING_MESSAGE);
            }
        }else{
            txtPesquisa.setText("Todos");
            carregaTabela();
        }    
    }//GEN-LAST:event_btnPesquisaActionPerformed

    private void jBtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEditarActionPerformed
        Produto p = new Produto();
        int index = jTbProduto.getSelectedRow();
        
        if(index == -1){
            JOptionPane.showMessageDialog(null,"É preciso selecionar um produto", "Aviso", JOptionPane.WARNING_MESSAGE);
        }else{    
            p = pro.getProdutos().get(index);
            JProdutoInserir2 jpi = new JProdutoInserir2(p);
            jpi.mostraTela(this);
       
        }
    }//GEN-LAST:event_jBtnEditarActionPerformed

    private void jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirActionPerformed
        // TODO add your handling code here:
        int escolha = JOptionPane.showConfirmDialog(this, "Deseja excluir produto?", "Excluir Produto",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if( escolha == 0){
        Produto p = new Produto();
                        
        int index = jTbProduto.getSelectedRow();
        p = pro.getProdutos().get(index);
        
        pro.deletarProduto(p.getId());
        
        carregaTabela();
       
        } 
    }//GEN-LAST:event_jBtnExcluirActionPerformed

    public void carregaTabela(){
           
        DefaultTableModel tblClientes = (DefaultTableModel)jTbProduto.getModel();
        
        tblClientes.setNumRows(0);
        
        for(Produto p: pro.getProdutos()){
            tblClientes.addRow(new Object []{
                p.getCodigo(),
                p.getNome(),
                nf.format(p.getPreco()),
                p.getQuantidade(),
                p.getCategoria(),
                p.getMarca()
            });
        }
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboPesquisa;
    private javax.swing.JButton btnPesquisa;
    private javax.swing.JButton jBtnEditar;
    private javax.swing.JButton jBtnExcluir;
    private javax.swing.JButton jBtnNovo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTbProduto;
    private javax.swing.JTextField txtPesquisa;
    // End of variables declaration//GEN-END:variables

}
