package com.devsakatsuki.perfumariapi2.view;

import com.devsakatsuki.perfumariapi2.dao.ConexaoBD;
import com.devsakatsuki.perfumariapi2.dao.VendaDAO;
import com.devsakatsuki.perfumariapi2.model.Venda;
import java.awt.Component;
import java.awt.Window;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;


public class JSelecaoRelatorio extends javax.swing.JFrame {

    ConexaoBD conexao = new ConexaoBD();
    VendaDAO vdao = new VendaDAO(conexao.abrirConexao());

    /**
     * Creates new form JSelecaoRelatorio
     */
    public JSelecaoRelatorio() {
        initComponents();
        setLocationRelativeTo(null);
        checkSintetico.setVisible(false);
        checkAnalitico.setVisible(false);
        lblSintetico.setVisible(false);
        lblAnalitico.setVisible(false);
    }

    public JSelecaoRelatorio(String relatorio) {
        initComponents();
        setLocationRelativeTo(null);
        checkSintetico.setVisible(false);
        checkAnalitico.setVisible(false);
        lblSintetico.setVisible(false);
        lblAnalitico.setVisible(false);

        if (relatorio.equalsIgnoreCase("Analítico")) {
            lblAnalitico.setVisible(true);
            checkAnalitico.setSelected(true);
        } else {
            lblSintetico.setVisible(true);
            checkSintetico.setSelected(true);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSintetico = new javax.swing.JLabel();
        lblAnalitico = new javax.swing.JLabel();
        checkSintetico = new javax.swing.JCheckBox();
        checkAnalitico = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        txtDataDe = new javax.swing.JFormattedTextField();
        txtDataAte = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnGerarRelatorio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblSintetico.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSintetico.setText("Relatório Sintético");

        lblAnalitico.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAnalitico.setText("Relatório Analítico");

        checkSintetico.setText("Rel Sintético");

        checkAnalitico.setText("Rel Analítico");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Período Venda", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        try {
            txtDataDe.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtDataAte.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel3.setText("De:");

        jLabel4.setText("Até:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDataDe, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtDataAte, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDataDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(txtDataAte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        btnGerarRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/report-icon_16.png"))); // NOI18N
        btnGerarRelatorio.setText("Gerar Relatório");
        btnGerarRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarRelatorioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSintetico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkSintetico)
                            .addComponent(checkAnalitico))
                        .addGap(10, 10, 10))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAnalitico)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 34, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(btnGerarRelatorio)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(checkSintetico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkAnalitico)
                    .addComponent(lblSintetico))
                .addGap(4, 4, 4)
                .addComponent(lblAnalitico)
                .addGap(38, 38, 38)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGerarRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGerarRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarRelatorioActionPerformed
        // TODO add your handling code here:
        if (txtDataDe.getText().contains("  /  /    ") || txtDataAte.getText().contains("  /  /    ")) {
            JOptionPane.showMessageDialog(null, "Campos data em branco", "Aviso", JOptionPane.WARNING_MESSAGE);
        }

        if (checkSintetico.isSelected()) {
            String[] datad = txtDataDe.getText().split("/");
            Calendar calendar = Calendar.getInstance();
            calendar.set(Integer.parseInt(datad[2]), Integer.parseInt(datad[1])-1, Integer.parseInt(datad[0]));
            Date dataDe = calendar.getTime();

            String[] dataa = txtDataAte.getText().split("/");
            Calendar calendar2 = Calendar.getInstance();
            calendar2.set(Integer.parseInt(dataa[2]), Integer.parseInt(dataa[1])-1, Integer.parseInt(dataa[0]));
            Date dataAte = calendar2.getTime();

            Calendar calendar3 = Calendar.getInstance();
            calendar3.setTime(dataDe);
            calendar3.add(Calendar.DATE, 30);
            Date data30 = calendar3.getTime();

            System.out.print(dataDe);
            System.out.print(dataAte);
            System.out.print(data30);

            if (dataDe.after(data30)) {
                JOptionPane.showMessageDialog(null, "Período maior que 30 dias", "Aviso", JOptionPane.WARNING_MESSAGE);
            }

            executeMostraTelaRelatorioSintetico(vdao.getRelatorios(dataDe, dataAte));

            Component comp = SwingUtilities.getRoot(this);
            ((Window) comp).dispose();
            
            conexao.fecharConexao();
            
        } else {

            String[] datad = txtDataDe.getText().split("/");
            Calendar calendar = Calendar.getInstance();
            calendar.set(Integer.parseInt(datad[2]), Integer.parseInt(datad[1]) - 1, Integer.parseInt(datad[0]));
            Date dataDe = calendar.getTime();

            String[] dataa = txtDataAte.getText().split("/");
            Calendar calendar2 = Calendar.getInstance();
            calendar2.set(Integer.parseInt(dataa[2]), Integer.parseInt(dataa[1]) - 1, Integer.parseInt(dataa[0]));
            Date dataAte = calendar2.getTime();

            Calendar calendar3 = Calendar.getInstance();
            calendar3.setTime(dataDe);
            calendar3.add(Calendar.DATE, 30);
            Date data30 = calendar3.getTime();

            System.out.print(dataDe);
            System.out.print(dataAte);
            System.out.print(data30);

            if (dataDe.after(data30)) {
                JOptionPane.showMessageDialog(null, "Período maior que 30 dias", "Aviso", JOptionPane.WARNING_MESSAGE);
            }

            executeMostraTelaRelatorioAnalitico(vdao.getRelatorios(dataDe, dataAte));

            Component comp = SwingUtilities.getRoot(this);
            ((Window) comp).dispose();
            
            conexao.fecharConexao();
        }
    }//GEN-LAST:event_btnGerarRelatorioActionPerformed

    private Principal principal;

    public void mostraTelaPrincipal(Principal p) {
        this.principal = p;
        setVisible(true);
    }

    public void executeMostraTelaRelatorioSintetico(List<Venda> vendas) {
        principal.carregaRelatoriosSintetico(vendas);
    }
    
    public void executeMostraTelaRelatorioAnalitico(List<Venda> vendas) {
        principal.carregaRelatoriosAnalitico(vendas);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JSelecaoRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JSelecaoRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JSelecaoRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JSelecaoRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JSelecaoRelatorio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGerarRelatorio;
    private javax.swing.JCheckBox checkAnalitico;
    private javax.swing.JCheckBox checkSintetico;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAnalitico;
    private javax.swing.JLabel lblSintetico;
    private javax.swing.JFormattedTextField txtDataAte;
    private javax.swing.JFormattedTextField txtDataDe;
    // End of variables declaration//GEN-END:variables
}
