/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.devsakatsuki.perfumariapi2.view;

import com.devsakatsuki.perfumariapi2.dao.ConexaoBD;
import com.devsakatsuki.perfumariapi2.dao.VendaDAO;
import com.devsakatsuki.perfumariapi2.model.Venda;
import java.awt.Component;
import java.awt.Window;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author 55119
 */
public class JSelecaoRelatorio extends javax.swing.JFrame {
    ConexaoBD conexao = new ConexaoBD();
    VendaDAO vdao = new VendaDAO(conexao.abrirConexao());
    /**
     * Creates new form JSelecaoRelatorio
     */
    public JSelecaoRelatorio() {
        initComponents();
        setLocationRelativeTo(null);
        checkSintetico.setVisible(false);
        checkAnalitico.setVisible(false);
        lblSintetico.setVisible(false);
        lblAnalitico.setVisible(false);
    }
    
    public JSelecaoRelatorio(String relatorio) {
        initComponents();
        setLocationRelativeTo(null);
        checkSintetico.setVisible(false);
        checkAnalitico.setVisible(false);
        lblSintetico.setVisible(false);
        lblAnalitico.setVisible(false);
                
        if(relatorio.equalsIgnoreCase("Analítico")){
            lblAnalitico.setVisible(true);
            checkAnalitico.setSelected(true);
        }else{
            lblSintetico.setVisible(true);
            checkSintetico.setSelected(true);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSintetico = new javax.swing.JLabel();
        lblAnalitico = new javax.swing.JLabel();
        txtDataDe = new javax.swing.JFormattedTextField();
        txtDataAte = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnGerarRelatorio = new javax.swing.JButton();
        checkSintetico = new javax.swing.JCheckBox();
        checkAnalitico = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblSintetico.setText("Relatório Sintético");

        lblAnalitico.setText("Relatório Analítico");

        try {
            txtDataDe.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtDataAte.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel3.setText("De:");

        jLabel4.setText("Até:");

        btnGerarRelatorio.setText("Gerar Relatório");
        btnGerarRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarRelatorioActionPerformed(evt);
            }
        });

        checkSintetico.setText("Rel Sintético");

        checkAnalitico.setText("Rel Analítico");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSintetico)
                            .addComponent(lblAnalitico))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkSintetico)
                            .addComponent(checkAnalitico))
                        .addGap(10, 10, 10))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(134, 134, 134)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtDataDe, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(txtDataAte, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(btnGerarRelatorio)))
                        .addContainerGap(42, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSintetico)
                    .addComponent(checkSintetico))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAnalitico)
                    .addComponent(checkAnalitico))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDataDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDataAte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnGerarRelatorio)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGerarRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarRelatorioActionPerformed
        // TODO add your handling code here:
        if(checkSintetico.isSelected()){
        String[] datad = txtDataDe.getText().split("/");
        String[] dataa = txtDataDe.getText().split("/");
        Calendar calendar = Calendar.getInstance(); 
        Calendar calendar2 = Calendar.getInstance(); 
        calendar.set(Integer.parseInt(datad[2]), Integer.parseInt(datad[1])-1, Integer.parseInt(datad[0]));
        calendar2.set(Integer.parseInt(dataa[2]), Integer.parseInt(dataa[1])-1, Integer.parseInt(dataa[0]));
        Date dataDe = calendar.getTime();
        Date dataAte = calendar2.getTime();
        calendar2.add(Calendar.DATE, 30);
        Date data30 = calendar2.getTime();
        
        if(dataDe.after(data30)){
            JOptionPane.showMessageDialog(null,"Período maior que 30 dias", "Aviso", JOptionPane.WARNING_MESSAGE);            
        }
        
        Component comp = SwingUtilities.getRoot(this);
        ((Window) comp).dispose();
        
        executeMostraTelaRelatorio("Sintetico", vdao.getRelatorios(dataDe, dataAte));
            
            
        }else{
        String[] datad = txtDataDe.getText().split("/");
        String[] dataa = txtDataDe.getText().split("/");
        Calendar calendar = Calendar.getInstance(); 
        Calendar calendar2 = Calendar.getInstance(); 
        calendar.set(Integer.parseInt(datad[2]), Integer.parseInt(datad[1])-1, Integer.parseInt(datad[0]));
        calendar2.set(Integer.parseInt(dataa[2]), Integer.parseInt(dataa[1])-1, Integer.parseInt(dataa[0]));
        Date dataDe = calendar.getTime();
        Date dataAte = calendar2.getTime();
        calendar2.add(Calendar.DATE, 30);
        Date data30 = calendar2.getTime();
        
        if(dataDe.after(data30)){
            JOptionPane.showMessageDialog(null,"Período maior que 30 dias", "Aviso", JOptionPane.WARNING_MESSAGE);            
        }    
        
        Component comp = SwingUtilities.getRoot(this);
        ((Window) comp).dispose();
        
        executeMostraTelaRelatorio("Analitico", vdao.getRelatorios(dataDe, dataAte));
        }
    }//GEN-LAST:event_btnGerarRelatorioActionPerformed
    
    private Principal principal;
    public void mostraTelaPrincipal(Principal p){
        this.principal = p;
        setVisible(true);
    }
    
    public void executeMostraTelaRelatorio(String tipo, List<Venda> vendas){
        principal.carregaRelatorios(tipo, vendas);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JSelecaoRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JSelecaoRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JSelecaoRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JSelecaoRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JSelecaoRelatorio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGerarRelatorio;
    private javax.swing.JCheckBox checkAnalitico;
    private javax.swing.JCheckBox checkSintetico;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblAnalitico;
    private javax.swing.JLabel lblSintetico;
    private javax.swing.JFormattedTextField txtDataAte;
    private javax.swing.JFormattedTextField txtDataDe;
    // End of variables declaration//GEN-END:variables
}
