package com.devsakatsuki.perfumariapi2.view;

import com.devsakatsuki.perfumariapi2.dao.ClienteDAO;
import com.devsakatsuki.perfumariapi2.dao.ConexaoBD;
import com.devsakatsuki.perfumariapi2.dao.ProdutoDAO;
import com.devsakatsuki.perfumariapi2.dao.VendaDAO;
import com.devsakatsuki.perfumariapi2.model.Cliente;
import com.devsakatsuki.perfumariapi2.model.ItemVenda;
import com.devsakatsuki.perfumariapi2.model.Produto;
import com.devsakatsuki.perfumariapi2.model.Venda;
import com.devsakatsuki.perfumariapi2.tablemodel.ItemVendaTableModel;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import javax.swing.JOptionPane;

public class JVendas2 extends javax.swing.JInternalFrame {

    ConexaoBD conexao = new ConexaoBD();
    ProdutoDAO pdao = new ProdutoDAO(conexao.abrirConexao());
    ClienteDAO cdao = new ClienteDAO(conexao.abrirConexao());
    VendaDAO vdao = new VendaDAO(conexao.abrirConexao());

    Venda venda = new Venda();

    Locale br = new Locale("pt", "Brazil");
    NumberFormat nf = NumberFormat.getInstance(br);
    NumberFormat nfc = NumberFormat.getCurrencyInstance();

    SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");

    public JVendas2() {
        initComponents();

        ftxtData.setText(dateFormat.format(new Date(System.currentTimeMillis())));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlProdutos = new javax.swing.JPanel();
        JSeparator1 = new javax.swing.JSeparator();
        lblQuantidade = new javax.swing.JLabel();
        lblProduto = new javax.swing.JLabel();
        btnAdicionarProduto = new javax.swing.JButton();
        lblPreco = new javax.swing.JLabel();
        lblProdutos = new javax.swing.JLabel();
        spnQuantidade = new javax.swing.JSpinner();
        btnPesquisarProduto = new javax.swing.JButton();
        ftxtPreco = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        ftxtProduto = new javax.swing.JFormattedTextField();
        pnlItensVenda = new javax.swing.JPanel();
        lblTotal = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblItensVenda = new javax.swing.JTable();
        btnRemoverItens = new javax.swing.JButton();
        ftxtValorTotal = new javax.swing.JFormattedTextField();
        btnFinalizarVenda = new javax.swing.JButton();
        btnCancelarVenda = new javax.swing.JButton();
        pnlDadosVenda = new javax.swing.JPanel();
        lblDadosVenda = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblData = new javax.swing.JLabel();
        btnPesquisarCliente = new javax.swing.JButton();
        lblCliente = new javax.swing.JLabel();
        ftxtData = new javax.swing.JFormattedTextField();
        ftxtCliente = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        setTitle("Venda");

        pnlProdutos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlProdutos.setPreferredSize(new java.awt.Dimension(516, 184));

        lblQuantidade.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblQuantidade.setText("Quantidade:");

        lblProduto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblProduto.setText("Produto:");

        btnAdicionarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/novo.png"))); // NOI18N
        btnAdicionarProduto.setText("Adicionar");
        btnAdicionarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarProdutoActionPerformed(evt);
            }
        });

        lblPreco.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblPreco.setText("Preço:");

        lblProdutos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblProdutos.setText("Produtos");

        spnQuantidade.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        btnPesquisarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pesquisar.png"))); // NOI18N
        btnPesquisarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarProdutoActionPerformed(evt);
            }
        });

        ftxtPreco.setEditable(false);

        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("*");

        ftxtProduto.setEditable(false);

        javax.swing.GroupLayout pnlProdutosLayout = new javax.swing.GroupLayout(pnlProdutos);
        pnlProdutos.setLayout(pnlProdutosLayout);
        pnlProdutosLayout.setHorizontalGroup(
            pnlProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProdutosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JSeparator1)
                    .addGroup(pnlProdutosLayout.createSequentialGroup()
                        .addGroup(pnlProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlProdutosLayout.createSequentialGroup()
                                .addComponent(lblProduto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblProdutos)
                            .addComponent(lblPreco)
                            .addComponent(lblQuantidade))
                        .addGap(18, 18, 18)
                        .addGroup(pnlProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlProdutosLayout.createSequentialGroup()
                                .addComponent(ftxtProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPesquisarProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(pnlProdutosLayout.createSequentialGroup()
                                .addGroup(pnlProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ftxtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spnQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(pnlProdutosLayout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addComponent(btnAdicionarProduto)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlProdutosLayout.setVerticalGroup(
            pnlProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProdutosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblProdutos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblProduto)
                        .addComponent(jLabel8)
                        .addComponent(ftxtProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnPesquisarProduto))
                .addGap(28, 28, 28)
                .addGroup(pnlProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnQuantidade)
                    .addComponent(lblQuantidade))
                .addGap(22, 22, 22)
                .addGroup(pnlProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ftxtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPreco))
                .addGap(26, 26, 26)
                .addComponent(btnAdicionarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pnlItensVenda.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Itens da Venda", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        pnlItensVenda.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        lblTotal.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblTotal.setText("Total:");

        tblItensVenda.setModel(new ItemVendaTableModel());
        tblItensVenda.setToolTipText("");
        jScrollPane1.setViewportView(tblItensVenda);

        btnRemoverItens.setIcon(new javax.swing.ImageIcon(getClass().getResource("/excluir.png"))); // NOI18N
        btnRemoverItens.setText("Excluir item");
        btnRemoverItens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverItensActionPerformed(evt);
            }
        });

        ftxtValorTotal.setEditable(false);
        ftxtValorTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        btnFinalizarVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalizar.png"))); // NOI18N
        btnFinalizarVenda.setText("Finalizar");
        btnFinalizarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarVendaActionPerformed(evt);
            }
        });

        btnCancelarVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cancelar.png"))); // NOI18N
        btnCancelarVenda.setText("Cancelar");
        btnCancelarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarVendaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlItensVendaLayout = new javax.swing.GroupLayout(pnlItensVenda);
        pnlItensVenda.setLayout(pnlItensVendaLayout);
        pnlItensVendaLayout.setHorizontalGroup(
            pnlItensVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlItensVendaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlItensVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlItensVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ftxtValorTotal)
                    .addComponent(btnFinalizarVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRemoverItens, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancelarVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlItensVendaLayout.setVerticalGroup(
            pnlItensVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlItensVendaLayout.createSequentialGroup()
                .addGroup(pnlItensVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
                    .addGroup(pnlItensVendaLayout.createSequentialGroup()
                        .addComponent(btnRemoverItens, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFinalizarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pnlItensVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ftxtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        pnlDadosVenda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblDadosVenda.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDadosVenda.setText("Dados da Venda");

        lblData.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblData.setText("Data Venda:");

        btnPesquisarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pesquisar.png"))); // NOI18N
        btnPesquisarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarClienteActionPerformed(evt);
            }
        });

        lblCliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCliente.setText("Cliente:");

        ftxtData.setEditable(false);
        try {
            ftxtData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftxtData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftxtDataActionPerformed(evt);
            }
        });

        ftxtCliente.setEditable(false);

        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("*");

        javax.swing.GroupLayout pnlDadosVendaLayout = new javax.swing.GroupLayout(pnlDadosVenda);
        pnlDadosVenda.setLayout(pnlDadosVendaLayout);
        pnlDadosVendaLayout.setHorizontalGroup(
            pnlDadosVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDadosVendaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDadosVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(lblDadosVenda)
                    .addGroup(pnlDadosVendaLayout.createSequentialGroup()
                        .addComponent(lblData)
                        .addGap(18, 18, 18)
                        .addComponent(ftxtData, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlDadosVendaLayout.createSequentialGroup()
                        .addComponent(lblCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(ftxtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPesquisarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlDadosVendaLayout.setVerticalGroup(
            pnlDadosVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDadosVendaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDadosVenda)
                .addGroup(pnlDadosVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDadosVendaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pnlDadosVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDadosVendaLayout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(pnlDadosVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblCliente)
                                    .addComponent(jLabel7))
                                .addGap(31, 31, 31))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDadosVendaLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ftxtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25))))
                    .addGroup(pnlDadosVendaLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(btnPesquisarCliente)
                        .addGap(25, 25, 25)))
                .addGroup(pnlDadosVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblData)
                    .addComponent(ftxtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
                    .addComponent(pnlDadosVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(pnlItensVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(pnlItensVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(pnlDadosVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(pnlProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRemoverItensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverItensActionPerformed
        if (tblItensVenda.getSelectedRowCount() > 0) {
            int linha = tblItensVenda.getSelectedRow();
            ItemVendaTableModel ivtm = (ItemVendaTableModel) tblItensVenda.getModel();
            ItemVenda iv = ivtm.getRowValue(linha);

            if (JOptionPane.showConfirmDialog(this, "Deseja realmente excluir o item " + iv + "?", "Confirmação", JOptionPane.YES_NO_OPTION) == 0) {
                venda.removeItem(iv);
                ivtm.setDados(venda.getItens());
                ftxtValorTotal.setValue(nfc.format(venda.calculaValorTotal()));
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecione uma linha para remover.", "Alerta", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_btnRemoverItensActionPerformed

    private void btnAdicionarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarProdutoActionPerformed
        ItemVenda iv = new ItemVenda();
        
        if (ftxtProduto.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Selecione um produto", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        Produto prod = (Produto) ftxtProduto.getValue();        
        if (prod.getQuantidade() > 0) {
            iv.setProduto((Produto) ftxtProduto.getValue());
            iv.setVenda(venda);
            if (prod.getQuantidade() >= (int) spnQuantidade.getValue()) {
                iv.setQuantidade((int) spnQuantidade.getValue());
            } else {
                JOptionPane.showMessageDialog(null, "Não há quantidades suficientes. " + prod.getQuantidade() + " Quantidades disponíveis.", "Aviso", JOptionPane.WARNING_MESSAGE);
            }
            iv.setValorUnitario(prod.getPreco());
            if ((int) spnQuantidade.getValue() > 0 && (int) spnQuantidade.getValue() <= prod.getQuantidade()) {
                venda.addItem(iv);
            } else {
                JOptionPane.showMessageDialog(null, "Escolha a quantidade.", "Aviso", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Não há produto no estoque.", "Aviso", JOptionPane.WARNING_MESSAGE);
        }

        ItemVendaTableModel ivtm = (ItemVendaTableModel) tblItensVenda.getModel();
        ivtm.setDados(venda.getItens());

        ftxtValorTotal.setValue(nfc.format(venda.calculaValorTotal()));
    }//GEN-LAST:event_btnAdicionarProdutoActionPerformed

    private void ftxtDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftxtDataActionPerformed

    }//GEN-LAST:event_ftxtDataActionPerformed

    private void btnFinalizarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarVendaActionPerformed
        //Metodo para setar data salvar
        String[] data = ftxtData.getText().split("/");
        Calendar calendar = Calendar.getInstance();
        calendar.set(Integer.parseInt(data[2]), Integer.parseInt(data[1]) - 1, Integer.parseInt(data[0]));
        Date dataVenda = calendar.getTime();

        int opcao = JOptionPane.showConfirmDialog(this, "Deseja realmente finalizar a venda?");
        if (opcao == 0) {
        
        if (ftxtCliente.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Obrigatório selecionar um cliente", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (ftxtValorTotal.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Adicione o(s) produto(s) na venda", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
 
            venda.setCliente(venda.getCliente());
            venda.setDataVenda(dataVenda);
            venda.setValorTotal(venda.calculaValorTotal());

            try {
                vdao.inserirVenda(venda);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Erro ao inserir a venda.\n" + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
                return;
            }
                JOptionPane.showMessageDialog(this, "Venda cadastrada com sucesso!");
             
            limpaVenda();
            venda = new Venda();
        }
    }//GEN-LAST:event_btnFinalizarVendaActionPerformed

    private void btnPesquisarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarClienteActionPerformed
        JBuscarCliente buscarCliente = new JBuscarCliente(this);
        buscarCliente.setVisible(true);
    }//GEN-LAST:event_btnPesquisarClienteActionPerformed

    private void btnPesquisarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarProdutoActionPerformed
        JBuscarProduto buscarProduto = new JBuscarProduto(this);
        buscarProduto.setVisible(true);
    }//GEN-LAST:event_btnPesquisarProdutoActionPerformed

    private void btnCancelarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarVendaActionPerformed
        int opcao = JOptionPane.showConfirmDialog(this, "Deseja realmente cancelar a venda?");
        if (opcao == 0) {
            limpaVenda();
            venda = new Venda();
        }
    }//GEN-LAST:event_btnCancelarVendaActionPerformed

    private void limpaVenda() {
        venda = null;
        ftxtValorTotal.setValue(null);
        tblItensVenda.setModel(new ItemVendaTableModel());
        spnQuantidade.setValue(1);
        ftxtCliente.setValue(null);
        ftxtProduto.setValue(null);
        ftxtPreco.setValue(null);
    }

    public void setClienteText(Cliente cliente) {
        ftxtCliente.setValue(cliente);
    }
    
    public void setProdutoText(Produto produto){
        ftxtProduto.setValue(produto);
        ftxtPreco.setValue(nfc.format(produto.getPreco()));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator JSeparator1;
    private javax.swing.JButton btnAdicionarProduto;
    private javax.swing.JButton btnCancelarVenda;
    private javax.swing.JButton btnFinalizarVenda;
    private javax.swing.JButton btnPesquisarCliente;
    private javax.swing.JButton btnPesquisarProduto;
    private javax.swing.JButton btnRemoverItens;
    private javax.swing.JFormattedTextField ftxtCliente;
    private javax.swing.JFormattedTextField ftxtData;
    private javax.swing.JFormattedTextField ftxtPreco;
    private javax.swing.JFormattedTextField ftxtProduto;
    private javax.swing.JFormattedTextField ftxtValorTotal;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblDadosVenda;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblPreco;
    private javax.swing.JLabel lblProduto;
    private javax.swing.JLabel lblProdutos;
    private javax.swing.JLabel lblQuantidade;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JPanel pnlDadosVenda;
    private javax.swing.JPanel pnlItensVenda;
    private javax.swing.JPanel pnlProdutos;
    private javax.swing.JSpinner spnQuantidade;
    private javax.swing.JTable tblItensVenda;
    // End of variables declaration//GEN-END:variables

}
